clone_twitter/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="date")
     */
    private $birthdate;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeInterface $birthdate): self
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        $creatAt = $this->creatAt;
        // guarantee every user at least has ROLE_USER
        $creatAt = new \DateTime();

        return $this->creatAt;
    }

    public function setCreatedAt(?\DateTimeInterface $creatAt): self
    {
        $this->creatAt = $creatAt;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Entity/Follows.php
<?php

namespace App\Entity;

use App\Repository\FollowsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FollowsRepository::class)
 */
class Follows
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $following;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $followers;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $createAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $updateAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $has_follow;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFollowing(): ?string
    {
        return $this->following;
    }

    public function setFollowing(string $following): self
    {
        $this->following = $following;

        return $this;
    }

    public function getFollowers(): ?string
    {
        return $this->followers;
    }

    public function setFollowers(string $followers): self
    {
        $this->followers = $followers;

        return $this;
    }

    public function getCreateAt(): ?string
    {
        return $this->createAt;
    }

    public function setCreateAt(string $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function getUpdateAt(): ?string
    {
        return $this->updateAt;
    }

    public function setUpdateAt(?string $updateAt): self
    {
        $this->updateAt = $updateAt;

        return $this;
    }

    public function getHasFollow(): ?bool
    {
        return $this->has_follow;
    }

    public function setHasFollow(bool $has_follow): self
    {
        $this->has_follow = $has_follow;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email')
            ->add('password')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;


use App\Entity\Follows;
use App\Entity\Likes;
use App\Entity\Posts;
use App\Entity\Repost;
use App\Entity\User;
use App\Form\EditType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Exception\BadRequestException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
/**
 * @IsGranted("ROLE_USER")
 * @IsGranted("IS_AUTHENTICATED_FULLY")
 */
class UserController extends AbstractController
{
    private EntityManagerInterface $entityManager;
    private string $error = '';

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/dashboard", name="dashboard")
     * @return Response
     */
    public function dashboard(): Response
    {
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
            'user' => $this->getUser(),
        ]);
    }

    /*
    * @Route("/profile/{id}", name="user_profile", methods={"GET","POST"})
    * @param Request $request
    * @param User $user
    * @return Response
        */

    /*    public function profile(Request $request, User $user): Response
        {

            $repository = $this->getDoctrine()->getRepository(User::class);
            $product = $repository->find($user->getId());
            $user = new User();
            /*$user = new User(
            $this->getDoctrine()->getManager()->flush();


<<<<<<< HEAD
    /**
     * @Route("/{username}", name="user_profile")
     * @param Request $request
     * @return Response
     */
    public function index(Request $request, User $user, $username): Response
    {
        $form = $this->createForm(EditType::class);
        $form->handleRequest($request);
        $em = $this->getDoctrine()->getManager();
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $form->getData();
            $em->persist($user);
            $em->flush();
            return $this->redirectToRoute('user_profile');
        }

        $user = $em->getRepository(User::class)->findOneBy([
            'username' => $username
        ]);

        $post = $em->getRepository(Posts::class)->findBy([
//            'user_id' => $user->getUserId()->getUuid()
        ]);
//        dd($post);
        if (!$post) {
            $error = 'Pas de post ici';
        }

        $nbpost = $em->getRepository(Posts::class)->count([
            'id' => $post
        ]);
//        $query = 'SELECT count(posts.id) FROM posts, user, posts_user WHERE posts.id = posts_user.posts_id
//                                  AND user.id = posts_user.user_id AND user.id = '.$user->getId().' ';
//
//        $statement = $em->getConnection()->prepare($query);
//        $statement->execute();
//
//        $total_posts = $statement->fetchAll();
//        var_dump($query);


        return $this->render('user/index.html.twig', [
            'userForm' => $form->createView(),
            'controller_name' => 'UserController',
            'user' => $user,
            'posts' => $post,
            'nbposts' => $nbpost,
//            'total_posts' => $total_posts,
        ]);
    }
=======
            return $this->render('home/index.html.twig', [
                'user' => $user
            ]);
        }*/


>>>>>>> lounes

    /**
     * @Route("/update/profile", name="update_profile", methods={"POST"})
     * @param Request $request
     * @return Response
     */
    public function update(Request $request): Response
    {
//        dump($request->request->get('username'));
//        if (!$request->request->get('username') && !$request->request->get('bio') && !$request->request->get('location') &&!$request->request->get('birthday')
//        || $request->request->get('username') === "" || $request->request->get('bio') === "" || $request->request->get('location') === "" || $request->request->get('birthday') === "")
//        {
//            return new Response('Erreur lors la mise à jour du profil');
//        }
        $username = $request->request->get('username');
        $bio = $request->request->get('bio');
        $location = $request->request->get('location');
//        $birthday = $request->request->get('birthday');
//        dump($request->request->all());
        $user = $this->getUser();
        $user->setUsername($username);
        $user->setBio($bio);
        $user->setLocation($location);
//        $user->setBirthdate($birthday);
        $entityManager = $this->getDoctrine()->getManager();

        $entityManager->persist($user);
        $entityManager->flush();

        return $this->redirectToRoute('user_profile', [
            'user' => $this->getUser(),
        ]);
    }


    /**
     * @Route("/follow", name="ajax_follow")
     * @param Request $request
     * @return JsonResponse
     * @throws BadRequestException
     */
    public function ajaxFollow(Request $request): JsonResponse
    {
        /*   if (!$request->isXmlHttpRequest() ) {
                return new JsonResponse('Aucune donnée reçu');
            }*/
        // initialise les donnée a envoyé


        $follower = $request->request->get('username');
        $follows = new Follows();

        if ($follower !== '' || !$follower) {
            $getFollower = $this->entityManager->getRepository(User::class)->findOneBy(
                [
                    'username' =>  $follower
                ]
            );

            if (!$getFollower) {
                return new JsonResponse('aucun membre associé');
            }
            $follow_find = $this->entityManager->getRepository(Follows::class)->findBy([
                'following' => $this->getUser()->getId(),
                'followers' => $getFollower->getId()
            ]);

            if (!$follow_find){

                $follows->setFollowing($this->getUser()->getId())
                    ->setFollowers($getFollower->getId())
                    ->setCreateAt(date("Y-m-d H:i:s"))
                    ->setHasFollow(true);
                $this->entityManager->persist($follows);
                $this->entityManager->flush();
                return new JsonResponse(true);

            }
            $follow_find = $follow_find[0];

            if ($follow_find->getHasFollow() !== true){
                $follow_find->setHasFollow(true)
                            ->setUpdateAt(date("Y-m-d H:i:s"));

                $this->entityManager->flush();
                return new JsonResponse(true);

            }

            $follow_find->setUpdateAt(date("Y-m-d H:i:s"))
                         ->setHasFollow(false);

            $this->entityManager->flush();
            return new JsonResponse(false);




        }

        return new JsonResponse('Aucune follower idendifié');

    }


    /**
     * @Route("/{username}", name="user_profile")
     * @param Request $request
     * @param $username
     * @return Response
     */
    public function index(Request $request, $username): Response
    {

        $form = $this->createForm(EditType::class);
        $form->handleRequest($request);
        $em = $this->getDoctrine()->getManager();
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $form->getData();
            $em->persist($user);
            $em->flush();
            return $this->redirectToRoute('user_profile');
        }
        $post = $em->getRepository(Posts::class)->findAll();
        if (!$post) {
            $error = 'Pas de post ici';
        }
        $user = $em->getRepository(User::class)->findOneBy([
            'username' => $username
        ]);
        $follow_find = $this->entityManager->getRepository(Follows::class)->findBy([
            'following' => $this->getUser()->getId(),
            'followers' => (string) $user->getId()
        ]);

        return $this->render('user/index.html.twig', [
            'userForm' => $form->createView(),
            'controller_name' => 'UserController',
            'user' => $user,
            'posts' => "",
            'follow' => $follow_find[0],
//            'total_posts' => $total_posts,
        ]);
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ app.user.getName() }} (@{{ app.user.getUsername() }}) / Twitter{% endblock %}



{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
        /* Modal Content */
        .modal-content {
            background-color: #5d5d5d!important;
        }
    </style>
    <div id="content">
        <div id="homeDiv" class='sticky'><span id="contentHome" class='font20bold'>{{  app.user.getName()}}</span></div>
        {#    {% for total_post in total_posts %}#}
        {#        {{ dump(total_post) }}#}
        {#    {% endfor %}#}
        {% if follow is not null %}
                <div>
                    <button type="submit" class="btn-follow">
            {% if follow.hasFollow is same as(true) %}
             Unfollowing
                {% else %}
                    Follow
                    {% endif %}
                </button>
                </div>
            {%  endif %}
        <div id='whatsHappening'>
            <div id='whatsHapIcon'><i class="far fa-user-circle"></i></div><br><br>
            <div id='tweetEditor'>
                {% if user is not null %}
                    <p class="textarea" role="textbox">
                    <p>{{ user.name }} {{ user.firstname }}</p>
                    <p id="follower" data-username="{{ user.username }}">Bio: {{ user.username }}</p>
                    <p>{{ user.bio }}</p>
                    <div id='tweetIcons'>
                        <div id='tweetIconsLeft'>
                            <p>Naissance le {{ user.birthdate|date("d/m/Y")  }}</p>
                            <p>nb abonnements  nb abonnés</p>
                        </div>
                        <div id='tweetIconsRight'>
                            <button type="button" id='publishTweet' class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Éditer le profil</button>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
        {% for post in posts %}
            {% if post.userId.values[0].id is same as app.user.id %}
                <div class='individualTweet'>
                    <div class='tweetUserIcon'><i class="far fa-user-circle"></i></div>
                    <div class='individualContent'>
                        <div class='names'>
                            <div class='individualName'> {{ post.userId.values[0].name }}</div>
                            <div class="individualUsername">@ {{ post.userId.values | first }}</div>
                            <div class='dot'></div>
                            <div class="time"></div>
                        </div>
                        <div class="individualText">
                            {{ post.body }}
                        </div>
                        <div class='individualIcons'>
                            <div class='individualInfo iconComment'><i class="far fa-comment"></i><span
                                        class='individualNumber' id='comments'></span></div>
                            <div class='individualInfo iconRetweet'><i class="fas fa-retweet"></i><span
                                        class='individualNumber' id='retweets'></span></div>
                            <div class='individualInfo iconLike'><i class="far fa-heart"></i></i><span
                                        class='individualNumber' id='likes'></span></div>
                            <div class='individualInfo iconShare'><i class="far fa-share-square"></i></div>
                        </div>
                    </div>
                </div>
            {% endif %}

        {% endfor %}


        <!-- Modal -->
        <div class="" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialoeg">
                <div class="">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Éditer le profil</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form id="myForm" action="{{ path('update_profile') }}" method="POST">
<<<<<<< HEAD
                    <div class="modal-body">
                            <div class="form-group">
                                <span type="text" class="form-control" name="username" placeholder="" readonly="readonly">Username : {{ user.username }}</span>
                            </div>
                            <div class="form-group">
                                <span type="email" class="form-control" name="email" readonly="readonly">Email : {{ user.email }}</span>
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" name="bio" placeholder="Bio" rows="3"></textarea>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" name="location" placeholder="Location">
                            </div>
                            <div class="form-group">
                                <input type="date" class="form-control" name="birthday" placeholder="Birthdate">
=======
                        {% if user is not null %}

                            <div class="modal-body">
                                <div class="form-group">
                                    <span type="text" class="form-control" name="username" placeholder="" readonly="readonly">Username : {{ user.name }}</span>
                                </div>
                                <div class="form-group">
                                    <span type="email" class="form-control" name="email" readonly="readonly">Email : {{ user.email }}</span>
                                </div>
                                <div class="form-group">
                                    <textarea class="form-control" name="bio" placeholder="Bio" rows="3"></textarea>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name="location" placeholder="Location">
                                </div>
                                <div class="form-group">
                                    <input type="date" class="form-control" name="birthday" placeholder="Birthdate">
                                </div>
>>>>>>> lounes
                            </div>
                        {% endif %}
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" id="edit_profile" class="btn btn-primary">Save changes</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}